services:
  mongoquery-ai:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - GROQ_KEY=${GROQ_KEY}
    volumes:
      - .:/app
    container_name: mongoquery-ai
    restart: unless-stopped
